# Generated by Django 2.2.7 on 2020-06-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageapi',
            name='image_name',
        ),
    ]
