# Generated by Django 2.2.7 on 2020-06-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_imageapi_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='responseapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64', models.CharField(default='none', max_length=20000)),
                ('md5', models.CharField(default='none', max_length=50)),
                ('aes', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
