# Generated by Django 2.2.7 on 2020-06-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadimage',
        ),
        migrations.RemoveField(
            model_name='imageapi',
            name='basestring',
        ),
        migrations.RemoveField(
            model_name='imageapi',
            name='md5',
        ),
    ]
