# Generated by Django 2.2.7 on 2020-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200616_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseapi',
            name='base64',
            field=models.TextField(default='none', max_length=2000000),
        ),
    ]
